//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcCore.Business.DB0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserve
    {
        public int reserve_id { get; set; }
        public int resident_id { get; set; }
        public int facility_id { get; set; }
        public string name { get; set; }
        public string tel { get; set; }
        public int person { get; set; }
        public int state { get; set; }
        public string fail_info { get; set; }
        public System.DateTime day { get; set; }
        public System.TimeSpan s_time { get; set; }
        public System.TimeSpan e_time { get; set; }
        public System.DateTime i_InsertDatetime { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual Resident Resident { get; set; }
    }
}
